=== miloos/client-andelyn-ids/client-andelyn/andelyn-packet/v1.0.1/schema.json
{
    "$id": "http://ids.tetrascience.com/private-tetrascience-mloos/andelyn-packet/v1.0.1/schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["id"],
    "properties": {
      "id": {
        "type": "string"
      },
      "file_name": {
        "type": "string"
      },
      "method": {
        "type": "string"
      },
      "method_version": {
        "type": "string"
      },
      "start_date": {
        "type": "string",
        "format": "date-time"
      },
      "end_date": {
        "type": "string",
        "format": "date-time"
      },
      "status": {
        "type": "string"
      },
      "last_updated_by": {
        "type": "string"
      },
      "last_updated_date": {
        "type": "string",
        "format": "date-time"
      },
      "created_by": {
        "type": "string"
      },
      "created_date": {
        "type": "string",
        "format": "date-time"
      },
      "samples": {
        "type": "array",
        "items": {
          "type": "object",
          "required": ["id", "lot_number"],
          "properties": {
            "id": {
              "type": "string"
            },
            "lot_number": {
              "type": "string"
            },
            "specification": {
              "type": "string"
            },
            "result": {
              "type": "string"
            },
            "last_updated_by": {
              "type": "string"
            },
            "last_updated_date": {
              "type": "string",
              "format": "date-time"
            },
            "serial_number": {
              "type": "string"
            },     
            "requested_by": {
              "type": "string"
            },  
            "requested_by_date": {
              "type": "string",
              "format": "date-time"
            },     
            "assigned_by": {
              "type": "string"
            },  
            "assigned_by_date": {
              "type": "string",
              "format": "date-time"
            },
            "project": {
              "type": "string"
            },
            "cd_number": {
              "type": "string"
            },
            "client_name": {
              "type": "string"
            },
            "client_id": {
              "type": "string"
            },
            "serotype": {
              "type": "string"
            },
            "transgene": {
              "type": "string"
            },
            "product_id": {
              "type": "string"
            },
            "product": {
              "type": "string"
            },
            "product_type": {
              "type": "string"
            },  
            "anticipated_manufacture_date": {
              "type": "string",
              "format": "date-time"
            },  
            "date_of_manufacture": {
              "type": "string",
              "format": "date-time"
            },  
            "qa_assignee": {
              "type": "string"
            },  
            "number_of_sublots": {
              "type": "number"
            },
            "gmp_or_tox": {
              "type": "string"
            },
            "tevg_pr": {
              "type": "string"
            },
            "barcode": {
              "type": "string"
            },
            "cell_line": {
              "type": "string"
            },
            "production_grade": {
              "type": "string"
            },
            "plasmid_name": {
              "type": "string"
            },
            "plasmid_type": {
              "type": "string"
            },
            "antibiotic_resistance": {
              "type": "string"
            },
            "comments": {
              "type": "string"
            }
          }
        }
      },
      "comments": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  }

=== miloos/client-andelyn-ids/client-andelyn/andelyn-packet/v1.0.1/expected.json
{
    "id": "1234",
    "file_name": "1234.pdf",
    "method": "MD-ABCD-123",
    "method_version": "1",
    "start_date": "2018-03-15T17:07:07.245Z",
    "end_date": "2018-03-16T17:07:07.245Z",
    "status": "Completed",
    "last_updated_by": "Jeff",
    "last_updated_date": "2018-03-15T17:07:07.245Z",
    "created_by": "George",
    "created_date": "2018-03-15T17:07:07.245Z",
    "samples": [
        {
            "id": "ABC-123",
            "lot_number": "T001A0318ABC",
            "specification": "Report Result",
            "result": "<0.050 EU/mL",
            "last_updated_by": "James",
            "last_updated_date": "2018-03-15T17:07:07.245Z",
            "serial_number": "1",
            "requested_by": "Jim",
            "requested_by_date": "2018-03-15T17:07:07.245Z",
            "assigned_by": "John",
            "assigned_by_date": "2018-03-15T17:07:07.245Z",
            "project": "Manufacture of ABC123",
            "cd_number": "ADS-345",
            "client_name": "ABC Biotech Co",
            "client_id": "0012",
            "serotype": "AB12",
            "transgene": "UDAB",
            "product_id": "A",
            "product": "UDAB",
            "product_type": "GMP",
            "anticipated_manufacture_date": "2018-03-15T17:07:07.245Z",
            "date_of_manufacture": "2018-03-15T17:07:07.245Z",
            "qa_assignee": "Mary",
            "number_of_sublots": 1,
            "gmp_or_tox": "G",
            "tevg_pr": "PR",
            "barcode": "A12345353A",
            "cell_line": "123AB",
            "production_grade": "Research",
            "plasmid_name": "AA123: 432r",
            "plasmid_type": "Vector Plasmid",
            "antibiotic_resistance": "ABC",
            "comments": "This is my comments"
        }
    ],
    "comments": [
        "Comment One",
        "Comment Two"
    ]
}
